FileVersion = 1
Dependencies = {corlib = "*", SDL2 = "*", FreeType = "*"}

[Project]
Name = "Spyro Scope"
TargetType = "BeefGUIApplication"
StartupObject = "SpyroScope.Program"

[Platform.Windows]
FileVersion = "1.5.2"

[Configs.Debug.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"
TargetName = "$(ProjectName)_debug"

[Configs.Release.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"

[Configs.Paranoid.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"

[Configs.Test.Win64]
TargetDirectory = "$(WorkspaceDir)/dist"
